const agents = [
  {
    id: 1,
    name: "Agni Dey",
    age: 25,
    country: "United States",
    phoneNumber: "(+1) 202-555-0123",
    email: "agni@gmail.com",
    profileImg:
      "https://tse3.mm.bing.net/th/id/OIP.v0S0RoVHAZsy6TE91oFGdgHaE7?pid=Api&P=0&h=180",
    role: "Sales Agent",
    newLead: 55,
    contacted: 45,
    qualified: 20,
    proposalSend: 20,
    closed: 10,
    leadsUnderSixMonths: 565,
    leadsUnderOneYear: 1268,
    closedUnderSixMonths: 300,
    closedUnderOneYear: 695,
    status: "Active",
    manager: "John Doe",
    location: "Office",
    department: "Sales",
    joinedDate: "24th June 2024",
    performanceScore: Number(((5.5 + 5.3 + 1.8) / 3).toFixed(1)),
    salesInThisMonth: 125,
  },
  {
    id: 2,
    name: "Bipin Kumar",
    age: 25,
    country: "India",
    phoneNumber: "(+91) 98765-43210",
    email: "alok@gmail.com",
    profileImg:
      "https://tse3.mm.bing.net/th/id/OIP.Pm4T0c8FEOkBflN4Afn01gHaE8?pid=Api&P=0&h=180",
    role: "Sales Agent",
    newLead: 65,
    contacted: 50,
    qualified: 30,
    proposalSend: 30,
    closed: 15,
    leadsUnderSixMonths: 668,
    leadsUnderOneYear: 1453,
    closedUnderSixMonths: 483,
    closedUnderOneYear: 864,
    status: "Active",
    manager: "John Doe",
    location: "Office",
    department: "Sales",
    joinedDate: "25th July 2023",
    performanceScore: Number(((5.9 + 7.2 + 2.3) / 3).toFixed(1)),
    salesInThisMonth: 140,
  },
  {
    id: 3,
    name: "Suraj Karmakar",
    age: 24,
    country: "United Kingdom",
    phoneNumber: "(+44) 20-7946-0958",
    email: "akshay@gmail.com",
    profileImg:
      "https://tse3.mm.bing.net/th/id/OIP.ULVjkhSQ7XjredebRexCFQHaHa?pid=Api&P=0&h=180",
    role: "Sales Agent",
    newLead: 71,
    contacted: 55,
    qualified: 30,
    proposalSend: 30,
    closed: 20,
    leadsUnderSixMonths: 738,
    leadsUnderOneYear: 1493,
    closedUnderSixMonths: 467,
    closedUnderOneYear: 967,
    status: "Active",
    manager: "John Doe",
    location: "Office",
    department: "Sales",
    joinedDate: "15th April 2023",
    performanceScore: Number(((6.5 + 6.3 + 2.8) / 3).toFixed(1)),
    salesInThisMonth: 170,
  },
  {
    id: 4,
    name: "Jay Choudhary",
    age: 24,
    country: "Germany",
    phoneNumber: "(+49) 30-1234567",
    email: "puja@gmail.com",
    profileImg:
      "https://tse2.mm.bing.net/th/id/OIP.6M_tdY7Fbu5RvJ_A3B4xMwHaHa?pid=Api&P=0&h=180",
    role: "Sales Agent",
    newLead: 58,
    contacted: 40,
    qualified: 25,
    proposalSend: 25,
    closed: 10,
    leadsUnderSixMonths: 528,
    leadsUnderOneYear: 1029,
    closedUnderSixMonths: 257,
    closedUnderOneYear: 568,
    status: "Active",
    manager: "John Doe",
    location: "Office",
    department: "Sales",
    joinedDate: "31 March 2024",
    performanceScore: Number(((5.5 + 4.9 + 1.7) / 3).toFixed(1)),
    salesInThisMonth: 150,
  },
  {
    id: 5,
    name: "Punam Das",
    age: 31,
    country: "Brazil",
    phoneNumber: "(+55) 11-98765-4321",
    email: "punam@gmail.com",
    profileImg:
      "https://tse3.mm.bing.net/th/id/OIP.rG9MZmuCEeERpeSjkCRWowHaE8?pid=Api&P=0&h=180",
    role: "Senior Sales Agent",
    newLead: 39,
    contacted: 30,
    qualified: 27,
    proposalSend: 27,
    closed: 15,
    leadsUnderSixMonths: 649,
    leadsUnderOneYear: 1293,
    closedUnderSixMonths: 568,
    closedUnderOneYear: 967,
    status: "Active",
    manager: "John Doe",
    location: "Office",
    department: "Sales",
    joinedDate: "11th January 2020",
    performanceScore: Number(((7.5 + 8.8 + 3.8) / 3).toFixed(1)),
    salesInThisMonth: 400,
  },
  {
    id: 6,
    name: "Yash Coube",
    age: 25,
    country: "Japan",
    phoneNumber: "(+81) 3-1234-5678",
    email: "parag@gmail.com",
    profileImg:
      "https://tse1.mm.bing.net/th/id/OIP.fBsCxHaiO6Z7ZK2lPCacYAHaEn?pid=Api&P=0&h=180",
    role: "Sales Agent",
    newLead: 67,
    contacted: 50,
    qualified: 43,
    proposalSend: 43,
    closed: 30,
    leadsUnderSixMonths: 768,
    leadsUnderOneYear: 1568,
    closedUnderSixMonths: 532,
    closedUnderOneYear: 1209,
    status: "Active",
    manager: "John Doe",
    location: "Office",
    department: "Sales",
    joinedDate: "18th August 2023",
    performanceScore: Number(((7.7 + 6.9 + 4.5) / 3).toFixed(1)),
    salesInThisMonth: 300,
  },
  {
    id: 7,
    name: "Harsh Chatterjee",
    age: 30,
    country: "Australia",
    phoneNumber: "(+61) 4-1234-5678",
    email: "pankaj@gmail.com",
    profileImg:
      "https://tse3.mm.bing.net/th/id/OIP.qI3bUPlhbdJzxBT3utnchAHaHa?pid=Api&P=0&h=180",
    role: "Senior Sales Agent",
    newLead: 73,
    contacted: 60,
    qualified: 49,
    proposalSend: 49,
    closed: 35,
    leadsUnderSixMonths: 761,
    leadsUnderOneYear: 1452,
    closedUnderSixMonths: 492,
    closedUnderOneYear: 1167,
    status: "Active",
    manager: "John Doe",
    location: "Office",
    department: "Sales",
    joinedDate: "6 July 2020",
    performanceScore: Number(((8 + 6.5 + 4.8) / 3).toFixed(1)),
    salesInThisMonth: 350,
  },
  {
    id: 8,
    name: "Bibhushita Mondal",
    age: 24,
    country: "Nigeria",
    phoneNumber: "(+234) 803-123-4567",
    email: "bibhushita@gmail.com",
    profileImg:
      "https://tse2.mm.bing.net/th/id/OIP.VPZluT5vYM5Cr_PwQ1l35wHaEJ?pid=Api&P=0&h=180",
    role: "Sales Agent",
    newLead: 62,
    contacted: 50,
    qualified: 31,
    proposalSend: 31,
    closed: 25,
    leadsUnderSixMonths: 562,
    leadsUnderOneYear: 1395,
    closedUnderSixMonths: 421,
    closedUnderOneYear: 937,
    status: "Active",
    manager: "John Doe",
    location: "Office",
    department: "Sales",
    joinedDate: "21 October 2023",
    performanceScore: Number(((6.7 + 7.5 + 4) / 3).toFixed(1)),
    salesInThisMonth: 410,
  },
  {
    id: 9,
    name: "Chayan Das",
    age: 25,
    country: "France",
    phoneNumber: "(+33) 1-23-45-67-89",
    email: "chayan@gmail.com",
    profileImg:
      "https://tse1.mm.bing.net/th/id/OIP.2lkOl7cahPSl-CT2mRahbQHaFj?pid=Api&P=0&h=180",
    role: "Sales Agent",
    newLead: 53,
    contacted: 40,
    qualified: 32,
    proposalSend: 32,
    closed: 20,
    leadsUnderSixMonths: 675,
    leadsUnderOneYear: 1297,
    closedUnderSixMonths: 428,
    closedUnderOneYear: 867,
    status: "Active",
    manager: "John Doe",
    location: "Office",
    department: "Sales",
    joinedDate: "23 September 2024",
    performanceScore: Number(((6.7 + 6.3 + 3.8) / 3).toFixed(1)),
    salesInThisMonth: 370,
  },
  {
    id: 10,
    name: "Daya Pathak",
    age: 29,
    country: "China",
    phoneNumber: "(+86) 10-1234-5678",
    email: "daya@gmail.com",
    profileImg:
      "https://tse3.mm.bing.net/th/id/OIP.mRXJOoK6kn21VLfHqTZOcwHaHa?pid=Api&P=0&h=180",
    role: "Senior Sales Agent",
    newLead: 65,
    contacted: 50,
    qualified: 42,
    proposalSend: 42,
    closed: 30,
    leadsUnderSixMonths: 693,
    leadsUnderOneYear: 1394,
    closedUnderSixMonths: 438,
    closedUnderOneYear: 967,
    status: "Active",
    manager: "John Doe",
    location: "Office",
    department: "Sales",
    joinedDate: "14 February 2021",
    performanceScore: Number(((6.9 + 6.3 + 4.6) / 3).toFixed(1)),
    salesInThisMonth: 390,
  },
]

export default agents
