const agents = [
  {
    id: 1,
    name: "Agni Dey",
    age: 27,
    country: "United States",
    phoneNumber: "(+1) 202-555-0123",
    email: "agni@gmail.com",
  },
  {
    id: 2,
    name: "Alok Kumar",
    age: 27,
    country: "India",
    phoneNumber: "(+91) 98765-43210",
    email: "alok@gmail.com",
  },
  {
    id: 3,
    name: "Akshay Karmakar",
    age: 27,
    country: "United Kingdom",
    phoneNumber: "(+44) 20-7946-0958",
    email: "akshay@gmail.com",
  },
  {
    id: 4,
    name: "Puja Choudhary",
    age: 27,
    country: "Germany",
    phoneNumber: "(+49) 30-1234567",
    email: "puja@gmail.com",
  },
  {
    id: 5,
    name: "Punam Das",
    age: 27,
    country: "Brazil",
    phoneNumber: "(+55) 11-98765-4321",
    email: "punam@gmail.com",
  },
  {
    id: 6,
    name: "Parag Coube",
    age: 27,
    country: "Japan",
    phoneNumber: "(+81) 3-1234-5678",
    email: "parag@gmail.com",
  },
  {
    id: 7,
    name: "Pankaj Chatterjee",
    age: 27,
    country: "Australia",
    phoneNumber: "(+61) 4-1234-5678",
    email: "pankaj@gmail.com",
  },
  {
    id: 8,
    name: "Bibhushita Mondal",
    age: 27,
    country: "Nigeria",
    phoneNumber: "(+234) 803-123-4567",
    email: "bibhushita@gmail.com",
  },
  {
    id: 9,
    name: "Chayan Das",
    age: 27,
    country: "France",
    phoneNumber: "(+33) 1-23-45-67-89",
    email: "chayan@gmail.com",
  },
  {
    id: 10,
    name: "Daya Pathak",
    age: 27,
    country: "China",
    phoneNumber: "(+86) 10-1234-5678",
    email: "daya@gmail.com",
  },
]
