const leadsData = [
  {
    id: 1,
    name: "Krishna Patel",
    source: "Website",
    salesAgent: "Agni Dey",
    status: "New",
    tags: "Follow up",
    timeToClose: 30,
    priority: "Medium",
    closedAt: null,
  },
  {
    id: 2,
    name: "Aarav Sharma",
    source: "YouTube",
    salesAgent: "Bipin Kumar",
    status: "Contacted",
    tags: "High Value",
    timeToClose: 30,
    priority: "High",
    closedAt: null,
  },
  {
    id: 3,
    name: "Herr Florian Weber",
    source: "Instagram",
    salesAgent: "Suraj Karmakar",
    status: "Qualified",
    tags: "Follow up",
    timeToClose: null,
    priority: "Low",
    closedAt: "19th April 2026",
  },
  {
    id: 4,
    name: "Frau Anna Klein",
    source: "Facebook",
    salesAgent: "Jay Choudhary",
    status: "Proposal Sent",
    tags: "High Value",
    timeToClose: 30,
    priority: "Medium",
    closedAt: null,
  },
  {
    id: 5,
    name: "Sheikh Ahmed Zidane",
    source: "News Paper",
    salesAgent: "Punam Das",
    status: "New",
    tags: "Follow up",
    timeToClose: 30,
    priority: "High",
    closedAt: null,
  },
  {
    id: 6,
    name: "Fatima Zahra",
    source: "Referral",
    salesAgent: "Yash Coube",
    status: "Contacted",
    tags: "High Value",
    timeToClose: 30,
    priority: "Low",
    closedAt: null,
  },
  {
    id: 7,
    name: "Dr. James Harper",
    source: "Our Customers",
    salesAgent: "Harsh Chatterjee",
    status: "Qualified",
    tags: "Follow up",
    timeToClose: 30,
    priority: "Medium",
    closedAt: null,
  },
  {
    id: 8,
    name: "Olivia Brown",
    source: "Television Ad",
    salesAgent: "Bibhushita Mondal",
    status: "Proposal Sent",
    tags: "High Value",
    timeToClose: 30,
    priority: "High",
    closedAt: null,
  },
  {
    id: 9,
    name: "Emma Davis",
    source: "Google",
    salesAgent: "Chayan Das",
    status: "Contacted",
    tags: "Follow up",
    timeToClose: null,
    priority: "Low",
    closedAt: "21th April 2026",
  },
  {
    id: 10,
    name: "Hiroshi Tanaka-san",
    source: "Others",
    salesAgent: "Daya Pathak",
    status: "Qualified",
    tags: "High Value",
    timeToClose: 30,
    priority: "Medium",
    closedAt: null,
  },
  {
    id: 11,
    name: "Yumi Suzuki-san",
    source: "Website",
    salesAgent: "Agni Dey",
    status: "Proposal Sent",
    tags: "Follow up",
    timeToClose: 30,
    priority: "High",
    closedAt: null,
  },
  {
    id: 12,
    name: "Priya Singh",
    source: "Website",
    salesAgent: "Bipin Kumar",
    status: "New",
    tags: "High Value",
    timeToClose: 30,
    priority: "Low",
    closedAt: null,
  },
]

export default leadsData